### ISSUE TITLE
Punching doesn't bring you out of protection.

### ISSUE THREAD

**Issue by Ayria** [sharkbound/RocketModSpawnProtection#1]
When a player who is protected punches someone they are not brought out of the protected state.
I also want you to know that when a player first respawns/enters the server there is 3-5 seconds of visibility. In a game of snap reflexes that is quite a long time.

**Comment by sharkbound** [comment]
the visibility is more a issue of rocket i believe, since i believe it take a tiny bit to setup the player.

Also i will see if it is possible to stop protection when they punch

**Comment by Ayria** [comment]
Alright, thanks :P

**Comment by sharkbound** [comment]
Also il add a config option for the vanish delay, just in case it is a issue with the hardcoded delay

**Comment by sharkbound** [comment]
i added a vanish delay config option, try tweaking it and seeing if it solves the vanish not visibility issue your having

**Comment by sharkbound** [comment]
i added where punching will cancel protection
