### ISSUE TITLE
Suggestion: Force dequip on spawn

### ISSUE THREAD

**Issue by Ayria** [sharkbound/RocketModSpawnProtection#4]
For use of player loadout. Loadout automatically puts weapons in hand on spawn. If your plugin forced dequip then you can have a loadout without loosing your protection.

P.S You've been awesome with implementing all that you have, this is such a great plugin!

**Comment by sharkbound** [comment]
I appreciate the kind words! <3. 

I can add this in.

PS: Have you had any issues with infinite godmode after respawning? My server has had this issue where after respawning and protection cancels you get infinite godmode, but the weird thing is that its a strange gliched godmode where it cant be disabled even by going in/out of god using /god. Im not sure if its rocket or the plugin.

**Comment by sharkbound** [comment]
Added this on build number 10 and over :D

**Comment by Ayria** [comment]
I haven't had it, but we're still setting up. (Website, bots, etc)
If it does happen, I'll let you know and provide any relevant logs.

**Comment by Ayria** [comment]
I hope you don't mind, I shot you a friend request on steam (I'm Caffe Breve)
