### ISSUE TITLE
Cross Plugin Issue

### ISSUE THREAD

**Issue by AdminGSUK** [sharkbound/RocketModSpawnProtection#5]
Hi There,
This isn't really specifically a Advanced Spawn Protection issue, but a cross issue when this plugin and another plugin are used. Specifically the Rocket-Regions plugin.

Basically if a player has spawn protection from the ASP plugin, and enters a Rocket-Region area with Godmode set to True before the ASP protection has expired, they will get permanent god mode until they disconnect.

I was able to replicate this fairly easily using the latest builds of both plugins.

Many Thanks

**Comment by sharkbound** [comment]
i have had this issue on my server recently as well, im trying to work out a fix for it.

**Comment by sharkbound** [comment]
i added EnsureGodmodeWhileProtected config setting in the latest build of AdvancedSpawnProtection. see if it being set to false fixes this for u

**Comment by AdminGSUK** [comment]
Thank you very much!  I will test it today :)

**Comment by AdminGSUK** [comment]
Initial tests seem to indicate that it has resolved the issue! 
I'll keep testing but so far looking really good. Thank you so much for the speedy response!

**Comment by sharkbound** [comment]
Im gonna close this for now, if it happens again u should be able to reopen and comment again
